package io.tnboot.logging.util.colorful

/* @formatter:off */
@OptIn(ExperimentalUnsignedTypes::class) val RESET = Code(0U, 0U)
@OptIn(ExperimentalUnsignedTypes::class) val BOLD = Code(22U, 1U)
@OptIn(ExperimentalUnsignedTypes::class) val DIM = Code(22U, 2U)
@OptIn(ExperimentalUnsignedTypes::class) val ITALIC = Code(23U, 3U)
@OptIn(ExperimentalUnsignedTypes::class) val UNDERLINE = Code(24U, 4U)
@OptIn(ExperimentalUnsignedTypes::class) val INVERSE = Code(27U, 7U)
@OptIn(ExperimentalUnsignedTypes::class) val HIDDEN = Code(28U, 8U)
@OptIn(ExperimentalUnsignedTypes::class) val STRIKETHROUGH = Code(29U, 9U)
@OptIn(ExperimentalUnsignedTypes::class) val BLACK = Code(39U, 30U)
@OptIn(ExperimentalUnsignedTypes::class) val RED = Code(39U, 31U)
@OptIn(ExperimentalUnsignedTypes::class) val GREEN = Code(39U, 32U)
@OptIn(ExperimentalUnsignedTypes::class) val YELLOW = Code(39U, 33U)
@OptIn(ExperimentalUnsignedTypes::class) val BLUE = Code(39U, 34U)
@OptIn(ExperimentalUnsignedTypes::class) val MAGENTA = Code(39U, 35U)
@OptIn(ExperimentalUnsignedTypes::class) val CYAN = Code(39U, 36U)
@OptIn(ExperimentalUnsignedTypes::class) val WHITE = Code(39U, 37U)
@OptIn(ExperimentalUnsignedTypes::class) val BRIGHT_BLACK = Code(39U, 90U)
@OptIn(ExperimentalUnsignedTypes::class) val BRIGHT_RED = Code(39U, 91U)
@OptIn(ExperimentalUnsignedTypes::class) val BRIGHT_GREEN = Code(39U, 92U)
@OptIn(ExperimentalUnsignedTypes::class) val BRIGHT_YELLOW = Code(39U, 93U)
@OptIn(ExperimentalUnsignedTypes::class) val BRIGHT_BLUE = Code(39U, 94U)
@OptIn(ExperimentalUnsignedTypes::class) val BRIGHT_MAGENTA = Code(39U, 95U)
@OptIn(ExperimentalUnsignedTypes::class) val BRIGHT_CYAN = Code(39U, 96U)
@OptIn(ExperimentalUnsignedTypes::class) val BRIGHT_WHITE = Code(39U, 97U)
@OptIn(ExperimentalUnsignedTypes::class) val BG_BLACK = Code(49U, 40U)
@OptIn(ExperimentalUnsignedTypes::class) val BG_RED = Code(49U, 41U)
@OptIn(ExperimentalUnsignedTypes::class) val BG_GREEN = Code(49U, 42U)
@OptIn(ExperimentalUnsignedTypes::class) val BG_YELLOW = Code(49U, 43U)
@OptIn(ExperimentalUnsignedTypes::class) val BG_BLUE = Code(49U, 44U)
@OptIn(ExperimentalUnsignedTypes::class) val BG_MAGENTA = Code(49U, 45U)
@OptIn(ExperimentalUnsignedTypes::class) val BG_CYAN = Code(49U, 46U)
@OptIn(ExperimentalUnsignedTypes::class) val BG_WHITE = Code(49U, 47U)
@OptIn(ExperimentalUnsignedTypes::class) val BG_BRIGHT_BLACK = Code(49U, 100U)
@OptIn(ExperimentalUnsignedTypes::class) val BG_BRIGHT_RED = Code(49U, 101U)
@OptIn(ExperimentalUnsignedTypes::class) val BG_BRIGHT_GREEN = Code(49U, 102U)
@OptIn(ExperimentalUnsignedTypes::class) val BG_BRIGHT_YELLOW = Code(49U, 103U)
@OptIn(ExperimentalUnsignedTypes::class) val BG_BRIGHT_BLUE = Code(49U, 104U)
@OptIn(ExperimentalUnsignedTypes::class) val BG_BRIGHT_MAGENTA = Code(49U, 105U)
@OptIn(ExperimentalUnsignedTypes::class) val BG_BRIGHT_CYAN = Code(49U, 106U)
@OptIn(ExperimentalUnsignedTypes::class) val BG_BRIGHT_WHITE = Code(49U, 107U)
/* @formatter:on */
